AllCops:
  Exclude:
    - 'vendor/**'
    - 'spec/**'

Style/StringLiterals:
  Enabled: false

Style/Tab:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Metrics/MethodLength:
  Max: 20

Style/RedundantReturn:
  Enabled: false
