language: ruby
rvm:
  - 2.3.0
  - 2.2
  - 2.1

cache:
  directories:
    - ../bundle

addons:
  code_climate:
    repo_token: 9f9b4d284b06c2827320a8c0a736a8b51e6fbe705d8485d96fc08e7bc2301dc8

notifications:
  email: false
